# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
# RangersAppLog Source
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'

target 'ModooPlayDemo_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  
  # ModooPlay
  pod 'TGCenter'
  
  # 隐私
  pod 'TGCPrivacy'
  
  # ModooPlay 事件统计
  pod 'TGCEmbed'
  
  # Umeng
  pod 'TGCUmeng'
  
  # AppsFlyer
  pod 'TGCAppsFlyer'
  
  # 深度转化
  pod 'TGCRangersAppLog'
  pod 'RangersAppLog', '5.4.2', :subspecs => ['Core','Log','Unique']
  
  # 广告聚合
  pod 'TGCTaurusXAds'
  # 穿山甲
  pod 'TaurusXAdMediation_TikTok'
  # 优量汇
  pod 'TaurusXAdMediation_GDT'
  # 快手
  pod 'TaurusXAdMediation_KuaiShou'
  # Mobrain
  pod 'TaurusXAdMediation_Mobrain'
  pod 'TaurusXAd_Mobrain_TikTok'
  pod 'TaurusXAdMediation_TikTok'
  pod 'TaurusXAd_Mobrain_GDT'
  pod 'TaurusXAdMediation_GDT'
  pod 'TaurusXAd_Mobrain_KuaiShou'
  pod 'TaurusXAdMediation_KuaiShou'
  
  # 游戏防沉迷
  pod 'TGCAntiAddiction'
  
  # 微信登录
  pod 'TGCWeChat'
  
  # 客服系统
  pod 'TGCUdesk'
  
end
